# AndroidX support ကို ဖွင့်ပေးရန် (မဖြစ်မနေ လိုအပ်သည်)
android.useAndroidX=true

# အဟောင်း (Legacy Support Libraries) များကို AndroidX သို့ စက်ရုပ်အလိုအလျောက် ပြောင်းပေးရန်
android.enableJetifier=true

# Memory & Build Optimization (GitHub Actions အတွက်)
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Djava.awt.headless=true
org.gradle.configuration-cache=false
